import type { Level } from "@/types/quiz";

// Generated from https://api.quitech.online/levels; keep this snapshot bundled for offline startup.
export const offlineCatalogue: { levels: Level[]; totalQuestions: number } = {
  "levels": [
    {
      "id": "foundations",
      "name": "Core Foundations",
      "tagline": "Basic math, English, science, digital skills, and everyday reasoning refreshers.",
      "ageRange": "Ages 13+",
      "order": 1,
      "questionCount": 10500,
      "sections": [
        {
          "id": "foundations-mathematics",
          "title": "Mathematics",
          "description": "Core number work, the four operations, fractions and rounding. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Mathematics",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-mathematics",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-english",
          "title": "English",
          "description": "Opposites, plurals and verb tenses for foundation refreshers. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "English",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-english",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-science",
          "title": "Science Fundamentals",
          "description": "The human body, animals, plants and everyday science. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Science Fundamentals",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-science",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-social-studies",
          "title": "Civic & World Basics",
          "description": "Countries, community helpers, civics and map skills. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Civic & World Basics",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-social-studies",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-ict",
          "title": "Digital Basics",
          "description": "Computer parts, common programs and staying safe online. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Digital Basics",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-ict",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-money-time",
          "title": "Money & Time",
          "description": "Shopping change, prices, clocks and calendars. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Money & Time",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-money-time",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-reading",
          "title": "Reading & Grammar",
          "description": "Parts of speech, punctuation, spelling and sentences. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Reading & Grammar",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-reading",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-health",
          "title": "Health & Hygiene",
          "description": "Personal hygiene, nutrition, safety and staying well. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Health & Hygiene",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-health",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-reasoning",
          "title": "Practical Problem Solving",
          "description": "Number patterns and simple real-life word problems. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Practical Problem Solving",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-reasoning",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-arts",
          "title": "Creative Arts & Music",
          "description": "Colours, drawing, instruments and rhythm for foundation refreshers. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Creative Arts & Music",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-arts",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-times-tables",
          "title": "Times Tables",
          "description": "Multiplication facts from 2 to 12. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Times Tables",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-times-tables",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-division",
          "title": "Division Facts",
          "description": "Sharing equally and finding exact quotients. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Division Facts",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-division",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-fractions",
          "title": "Fractions",
          "description": "Halves, quarters and fractions of amounts. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Fractions",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-fractions",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-measures",
          "title": "Measurement & Units",
          "description": "Converting length, mass and capacity. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Measurement & Units",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-measures",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-time",
          "title": "Telling the Time",
          "description": "Reading clocks and working with minutes. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Telling the Time",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-time",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-money",
          "title": "Money & Shopping",
          "description": "Change, totals and simple budgeting. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Money & Shopping",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-money",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-rounding",
          "title": "Rounding & Estimation",
          "description": "Rounding to the nearest ten and hundred. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Rounding & Estimation",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-rounding",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-spelling",
          "title": "Spelling & Grammar",
          "description": "Plurals, tenses, punctuation and word classes. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Spelling & Grammar",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-spelling",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-wellbeing",
          "title": "Wellbeing Essentials",
          "description": "Staying clean, eating well and preventing illness. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Wellbeing Essentials",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-wellbeing",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-world",
          "title": "World Geography",
          "description": "Capitals, continents, rivers and landmarks. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "World Geography",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-world",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "foundations-place-value",
          "title": "Place Value",
          "description": "Tens, hundreds and thousands in whole numbers. Built for clear 13+ refreshers, steady confidence, and everyday learning momentum.",
          "category": "Place Value",
          "levelId": "foundations",
          "levelName": "Core Foundations",
          "sectionId": "foundations-place-value",
          "difficulty": "Easy",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        }
      ]
    },
    {
      "id": "secondary",
      "name": "Secondary Education",
      "tagline": "Focused 13+ revision across core secondary-level subjects.",
      "ageRange": "Ages 13+",
      "order": 2,
      "questionCount": 10500,
      "sections": [
        {
          "id": "secondary-algebra",
          "title": "Algebra",
          "description": "Linear equations, expressions, quadratics and graphs. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Algebra",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-algebra",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-geometry",
          "title": "Geometry & Mensuration",
          "description": "Area, perimeter, angles and circles. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Geometry & Mensuration",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-geometry",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-chemistry",
          "title": "Chemistry",
          "description": "Elements, bonding, acids, bases and reactions. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Chemistry",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-chemistry",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-physics",
          "title": "Physics",
          "description": "Forces, energy, waves, electricity and SI units. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Physics",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-physics",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-biology",
          "title": "Biology",
          "description": "Cells, human systems, plants, genetics and ecology. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Biology",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-biology",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-geography",
          "title": "Geography",
          "description": "Physical geography, maps, climate and world capitals. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Geography",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-geography",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-history",
          "title": "History & Government",
          "description": "World and African history, governance and citizenship. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "History & Government",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-history",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-literature",
          "title": "Literature & Comprehension",
          "description": "Figures of speech, literary terms and text analysis. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Literature & Comprehension",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-literature",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-business",
          "title": "Business Studies",
          "description": "Trade, costs, profit calculations and commerce basics. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Business Studies",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-business",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-computer",
          "title": "Computer Studies",
          "description": "Hardware, software, networks, binary and safe computing. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Computer Studies",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-computer",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-economics",
          "title": "Economics",
          "description": "Demand, supply, markets, trade and national income. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Economics",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-economics",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-agriculture",
          "title": "Agriculture",
          "description": "Soils, crops, livestock and farm management. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Agriculture",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-agriculture",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-trigonometry",
          "title": "Trigonometry",
          "description": "Sines, cosines and right-angle triangle work. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Trigonometry",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-trigonometry",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-statistics",
          "title": "Statistics & Probability",
          "description": "Mean, median, range and simple probability. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Statistics & Probability",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-statistics",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-physics-numeric",
          "title": "Applied Physics",
          "description": "Speed, force, work and electrical calculations. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Applied Physics",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-physics-numeric",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-chemistry-formulas",
          "title": "Chemistry Essentials",
          "description": "Formulas, symbols, bonding and atomic structure. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Chemistry Essentials",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-chemistry-formulas",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-human-biology",
          "title": "Human Biology",
          "description": "Cells, organs, systems and genetics. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Human Biology",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-human-biology",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-world-history",
          "title": "World History",
          "description": "Key events, leaders and turning points. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "World History",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-world-history",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-literature-in-english",
          "title": "Literature in English",
          "description": "Figures of speech, plot, poetry and drama. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Literature in English",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-literature-in-english",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-computer-systems",
          "title": "Computer Systems",
          "description": "Hardware, software, networks and data. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Computer Systems",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-computer-systems",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "secondary-algebra-drills",
          "title": "Algebra Drills",
          "description": "Solving linear equations and evaluating expressions. Built for focused revision, confident recall, and steady exam-style practice.",
          "category": "Algebra Drills",
          "levelId": "secondary",
          "levelName": "Secondary Education",
          "sectionId": "secondary-algebra-drills",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        }
      ]
    },
    {
      "id": "college",
      "name": "College & University",
      "tagline": "Degree-level reasoning and applied problem solving.",
      "ageRange": "Ages 18+",
      "order": 3,
      "questionCount": 11000,
      "sections": [
        {
          "id": "college-calculus",
          "title": "Calculus",
          "description": "Differentiation, integration and limits. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Calculus",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-calculus",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-statistics",
          "title": "Statistics",
          "description": "Descriptive statistics, distributions and hypothesis testing. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Statistics",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-statistics",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-programming",
          "title": "Computer Programming",
          "description": "Algorithms, data structures, OOP and web basics. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Computer Programming",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-programming",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-economics",
          "title": "College Economics",
          "description": "Micro and macro principles with applied calculations. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "College Economics",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-economics",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-digital-logic",
          "title": "Digital Logic",
          "description": "Number systems, logic gates and binary arithmetic. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Digital Logic",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-digital-logic",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-accounting",
          "title": "Accounting",
          "description": "Financial statements, double entry and ratios. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Accounting",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-accounting",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-linear-algebra",
          "title": "Linear Algebra",
          "description": "Matrices, determinants, vectors and vector spaces. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Linear Algebra",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-linear-algebra",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-databases",
          "title": "Databases & SQL",
          "description": "Relational design, SQL queries, transactions and scaling. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Databases & SQL",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-databases",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-engineering-physics",
          "title": "Engineering Physics",
          "description": "Mechanics, energy, materials, fluids and thermodynamics. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Engineering Physics",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-engineering-physics",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-management",
          "title": "Management & Marketing",
          "description": "Management functions, strategy, marketing and break-even analysis. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Management & Marketing",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-management",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-psychology",
          "title": "Psychology",
          "description": "Learning, memory, development, research methods and the brain. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Psychology",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-psychology",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-matrix-vector-algebra",
          "title": "Matrix & Vector Algebra",
          "description": "Determinants, matrices and vector operations. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Matrix & Vector Algebra",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-matrix-vector-algebra",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-probability",
          "title": "Probability Theory",
          "description": "Combinatorics, independence and expected value. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Probability Theory",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-probability",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-financial-accounting",
          "title": "Financial Accounting",
          "description": "Statements, double entry, ratios and standards. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Financial Accounting",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-financial-accounting",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-business-law",
          "title": "Business Law",
          "description": "Contracts, torts, companies and intellectual property. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Business Law",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-business-law",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-data-structures",
          "title": "Data Structures & Algorithms",
          "description": "Complexity, sorting, trees and graphs. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Data Structures & Algorithms",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-data-structures",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-operating-systems",
          "title": "Operating Systems",
          "description": "Processes, memory, scheduling and file systems. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Operating Systems",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-operating-systems",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-environmental-science",
          "title": "Environmental Science",
          "description": "Ecosystems, pollution, climate and sustainability. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Environmental Science",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-environmental-science",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-research-methods",
          "title": "Research Methods",
          "description": "Design, sampling, validity, statistics and ethics. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Research Methods",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-research-methods",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-percentages-finance",
          "title": "Business Mathematics",
          "description": "Interest, percentages and financial calculations. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Business Mathematics",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-percentages-finance",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-calculus-drills",
          "title": "Calculus Drills",
          "description": "Differentiating and integrating polynomial terms. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Calculus Drills",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-calculus-drills",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "college-project-management",
          "title": "Project Management",
          "description": "Scope, schedule, risk, quality and stakeholder control. Built for higher-level practice, applied reasoning, and certificate-ready review.",
          "category": "Project Management",
          "levelId": "college",
          "levelName": "College & University",
          "sectionId": "college-project-management",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        }
      ]
    },
    {
      "id": "professional",
      "name": "Professional",
      "tagline": "Workplace certification practice across every department.",
      "ageRange": "Career learners",
      "order": 4,
      "questionCount": 11500,
      "sections": [
        {
          "id": "professional-electrical",
          "title": "Electrical Engineering",
          "description": "Ohm's law, circuits, machines, protection and site safety. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Electrical Engineering",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-electrical",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-it",
          "title": "IT & Networking",
          "description": "Protocols, ports, subnetting, security and operations. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "IT & Networking",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-it",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-finance",
          "title": "Business & Finance",
          "description": "Strategy, financial analysis and interest calculations. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Business & Finance",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-finance",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-project-management",
          "title": "Professional Project Management",
          "description": "Scope, schedule, risk, agile and stakeholder management. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Professional Project Management",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-project-management",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-safety",
          "title": "Health & Safety",
          "description": "Risk assessment, PPE, fire, electrical and site safety. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Health & Safety",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-safety",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-data-ai",
          "title": "Data & AI",
          "description": "Machine learning, data engineering and model evaluation. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Data & AI",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-data-ai",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-iot",
          "title": "IoT & Embedded Systems",
          "description": "Sensors, microcontrollers, MQTT, edge computing and device security. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "IoT & Embedded Systems",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-iot",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-automation",
          "title": "Automation & Control",
          "description": "PLCs, SCADA, PID control, instrumentation and industrial safety. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Automation & Control",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-automation",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-cybersecurity",
          "title": "Cybersecurity",
          "description": "Threats, cryptography, hardening, incident response and governance. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Cybersecurity",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-cybersecurity",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-mechanical",
          "title": "Mechanical Engineering",
          "description": "Materials, machine elements, torque, stress and maintenance. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Mechanical Engineering",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-mechanical",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-civil",
          "title": "Civil & Structural Engineering",
          "description": "Concrete, foundations, structures, surveying and site management. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Civil & Structural Engineering",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-civil",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-healthcare",
          "title": "Healthcare & Nursing",
          "description": "Vital signs, emergency care, infection control and patient safety. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Healthcare & Nursing",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-healthcare",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-agriculture",
          "title": "Agriculture & Agribusiness",
          "description": "Soils, crops, livestock, post-harvest handling and farm economics. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Agriculture & Agribusiness",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-agriculture",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-hr",
          "title": "Human Resources",
          "description": "Recruitment, performance, employment relations and HR policy. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Human Resources",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-hr",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-law",
          "title": "Law, Ethics & Compliance",
          "description": "Contracts, liability, data protection and regulatory compliance. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Law, Ethics & Compliance",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-law",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-automotive",
          "title": "Automotive & Mechatronics",
          "description": "Engines, diagnostics, braking, EV systems and servicing. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Automotive & Mechatronics",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-automotive",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-cloud",
          "title": "Cloud & DevOps",
          "description": "Cloud models, containers, CI/CD, reliability and cloud security. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Cloud & DevOps",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-cloud",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-marketing",
          "title": "Marketing & Growth",
          "description": "Segmentation, funnels, digital channels and campaign metrics. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Marketing & Growth",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-marketing",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-logistics",
          "title": "Logistics & Supply Chain",
          "description": "Inventory, warehousing, incoterms and distribution performance. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Logistics & Supply Chain",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-logistics",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-telecom",
          "title": "Telecommunications",
          "description": "Mobile networks, fibre, multiplexing and service quality. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Telecommunications",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-telecom",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-renewable-energy",
          "title": "Renewable Energy",
          "description": "Solar, wind, storage, grid integration and efficiency. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Renewable Energy",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-renewable-energy",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-aviation",
          "title": "Aviation Operations",
          "description": "Flight principles, instruments, airspace and safety procedures. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Aviation Operations",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-aviation",
          "difficulty": "Hard",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "professional-hospitality",
          "title": "Hospitality & Food Safety",
          "description": "Front office, housekeeping, kitchen standards and guest metrics. Built for practical workplace review, interview preparation, and certification practice.",
          "category": "Hospitality & Food Safety",
          "levelId": "professional",
          "levelName": "Professional",
          "sectionId": "professional-hospitality",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        }
      ]
    },
    {
      "id": "popular-topics",
      "name": "Popular Topics",
      "tagline": "Take on the subjects people love most, from football to gaming.",
      "ageRange": "Ages 13+",
      "order": 5,
      "questionCount": 12000,
      "sections": [
        {
          "id": "popular-football",
          "title": "Football",
          "description": "Clubs, competitions, rules, players and football history. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Football",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-football",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-manchester-united",
          "title": "Manchester United",
          "description": "Manchester United history, Old Trafford, identity and rivalries. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Manchester United",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-manchester-united",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-chelsea",
          "title": "Chelsea",
          "description": "Chelsea history, Stamford Bridge, identity and London rivalries. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Chelsea",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-chelsea",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-arsenal",
          "title": "Arsenal",
          "description": "Arsenal history, the Emirates Stadium, identity and North London rivalry. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Arsenal",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-arsenal",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-liverpool",
          "title": "Liverpool",
          "description": "Liverpool history, Anfield, identity and Merseyside rivalries. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Liverpool",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-liverpool",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-manchester-city",
          "title": "Manchester City",
          "description": "Manchester City history, the Etihad Stadium, identity and Manchester rivalry. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Manchester City",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-manchester-city",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-tottenham",
          "title": "Tottenham Hotspur",
          "description": "Tottenham Hotspur history, stadium, identity and North London rivalry. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Tottenham Hotspur",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-tottenham",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-newcastle-united",
          "title": "Newcastle United",
          "description": "Newcastle United history, St James' Park, identity and North East football. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Newcastle United",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-newcastle-united",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-aston-villa",
          "title": "Aston Villa",
          "description": "Aston Villa history, Villa Park, identity and Birmingham rivalry. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Aston Villa",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-aston-villa",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-world-cup",
          "title": "World Cup",
          "description": "World Cup tournaments, nations, records and famous moments. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "World Cup",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-world-cup",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-premier-league",
          "title": "Premier League",
          "description": "English Premier League clubs, records, rules and rivalries. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Premier League",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-premier-league",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-champions-league",
          "title": "Champions League",
          "description": "UEFA Champions League clubs, finals, history and European competition. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Champions League",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-champions-league",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-la-liga",
          "title": "La Liga",
          "description": "Spanish league clubs, stadiums, players and football history. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "La Liga",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-la-liga",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-serie-a",
          "title": "Serie A",
          "description": "Italian league clubs, stadiums, tactics and football traditions. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Serie A",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-serie-a",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-bundesliga",
          "title": "Bundesliga",
          "description": "German league clubs, stadiums, supporters and football history. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Bundesliga",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-bundesliga",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-african-football",
          "title": "African Football",
          "description": "African clubs, nations, competitions and football development. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "African Football",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-african-football",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-womens-football",
          "title": "Women's Football",
          "description": "Women's football competitions, pioneers, clubs and international history. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Women's Football",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-womens-football",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-club-history",
          "title": "Club History",
          "description": "Football club origins, honours, rivalries, stadiums and traditions. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Club History",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-club-history",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-famous-players",
          "title": "Famous Players",
          "description": "Football legends, positions, records and playing styles. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Famous Players",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-famous-players",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-transfers",
          "title": "Transfers",
          "description": "Transfer windows, contracts, fees, scouting and player movement. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Transfers",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-transfers",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-football-rules",
          "title": "Football Rules",
          "description": "The laws of football, fouls, restarts, officials and match decisions. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Football Rules",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-football-rules",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-general-knowledge",
          "title": "General Knowledge",
          "description": "A broad challenge across science, history, geography and everyday facts. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "General Knowledge",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-general-knowledge",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-movies-music",
          "title": "Movies & Music",
          "description": "Film language, music theory, performers and entertainment culture. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Movies & Music",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-movies-music",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        },
        {
          "id": "popular-gaming",
          "title": "Gaming",
          "description": "Video game genres, mechanics, esports and gaming culture. Built for curious learners who want quick recall, challenge, and steady progress.",
          "category": "Gaming",
          "levelId": "popular-topics",
          "levelName": "Popular Topics",
          "sectionId": "popular-gaming",
          "difficulty": "Medium",
          "timeLimitSeconds": 15000,
          "questionCount": 500
        }
      ]
    }
  ],
  "totalQuestions": 55500
};

export const offlineSectionCount = 111;
