/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DeleteDataRouteImport } from './routes/delete-data'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiLevelsRouteImport } from './routes/api/levels'
import { Route as ApiSubmitRouteImport } from './routes/api/submit'
import { Route as CertificateIndexRouteImport } from './routes/certificate.index'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as ApiAdminAuditLogRouteImport } from './routes/api/admin/audit-log'
import { Route as ApiAdminCatalogueRouteImport } from './routes/api/admin/catalogue'
import { Route as ApiAdminCertificatesRouteImport } from './routes/api/admin/certificates'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiCertificatesCodeRouteImport } from './routes/api/certificates.$code'
import { Route as ApiQuizzesIndexRouteImport } from './routes/api/quizzes.index'
import { Route as ApiQuizzesIdRouteImport } from './routes/api/quizzes.$id'
import { Route as ApiAdminCatalogueSectionIdRouteImport } from './routes/api/admin/catalogue.$sectionId'
import { Route as ApiAdminLeaderboardIdRouteImport } from './routes/api/admin/leaderboard.$id'
import { Route as ApiAuthMeActivityRouteImport } from './routes/api/auth/me/activity'
import { Route as ApiAdminCatalogueSectionIdPublishRouteImport } from './routes/api/admin/catalogue.$sectionId.publish'
import { Route as ApiAuthMeProgressQuizIdRouteImport } from './routes/api/auth/me/progress.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteDataRoute = DeleteDataRouteImport.update({
  id: '/delete-data',
  path: '/delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLevelsRoute = ApiLevelsRouteImport.update({
  id: '/api/levels',
  path: '/api/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitRoute = ApiSubmitRouteImport.update({
  id: '/api/submit',
  path: '/api/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIndexRoute = CertificateIndexRouteImport.update({
  id: '/certificate/',
  path: '/certificate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditLogRoute = ApiAdminAuditLogRouteImport.update({
  id: '/api/admin/audit-log',
  path: '/api/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCatalogueRoute = ApiAdminCatalogueRouteImport.update({
  id: '/api/admin/catalogue',
  path: '/api/admin/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCertificatesRoute = ApiAdminCertificatesRouteImport.update({
  id: '/api/admin/certificates',
  path: '/api/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesCodeRoute = ApiCertificatesCodeRouteImport.update({
  id: '/api/certificates/$code',
  path: '/api/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizzesIndexRoute = ApiQuizzesIndexRouteImport.update({
  id: '/api/quizzes/',
  path: '/api/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizzesIdRoute = ApiQuizzesIdRouteImport.update({
  id: '/api/quizzes/$id',
  path: '/api/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCatalogueSectionIdRoute =
  ApiAdminCatalogueSectionIdRouteImport.update({
    id: '/$sectionId',
    path: '/$sectionId',
    getParentRoute: () => ApiAdminCatalogueRoute,
  } as any)
const ApiAdminLeaderboardIdRoute = ApiAdminLeaderboardIdRouteImport.update({
  id: '/api/admin/leaderboard/$id',
  path: '/api/admin/leaderboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeActivityRoute = ApiAuthMeActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiAuthMeRoute,
} as any)
const ApiAdminCatalogueSectionIdPublishRoute =
  ApiAdminCatalogueSectionIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiAdminCatalogueSectionIdRoute,
  } as any)
const ApiAuthMeProgressQuizIdRoute = ApiAuthMeProgressQuizIdRouteImport.update({
  id: '/progress/$quizId',
  path: '/progress/$quizId',
  getParentRoute: () => ApiAuthMeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/levels': typeof ApiLevelsRoute
  '/api/submit': typeof ApiSubmitRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/api/': typeof ApiIndexRoute
  '/certificate/': typeof CertificateIndexRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/catalogue': typeof ApiAdminCatalogueRouteWithChildren
  '/api/admin/certificates': typeof ApiAdminCertificatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/certificates/$code': typeof ApiCertificatesCodeRoute
  '/api/quizzes/$id': typeof ApiQuizzesIdRoute
  '/api/quizzes/': typeof ApiQuizzesIndexRoute
  '/api/admin/catalogue/$sectionId': typeof ApiAdminCatalogueSectionIdRouteWithChildren
  '/api/admin/leaderboard/$id': typeof ApiAdminLeaderboardIdRoute
  '/api/auth/me/activity': typeof ApiAuthMeActivityRoute
  '/api/admin/catalogue/$sectionId/publish': typeof ApiAdminCatalogueSectionIdPublishRoute
  '/api/auth/me/progress/$quizId': typeof ApiAuthMeProgressQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/levels': typeof ApiLevelsRoute
  '/api/submit': typeof ApiSubmitRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/api': typeof ApiIndexRoute
  '/certificate': typeof CertificateIndexRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/catalogue': typeof ApiAdminCatalogueRouteWithChildren
  '/api/admin/certificates': typeof ApiAdminCertificatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/certificates/$code': typeof ApiCertificatesCodeRoute
  '/api/quizzes/$id': typeof ApiQuizzesIdRoute
  '/api/quizzes': typeof ApiQuizzesIndexRoute
  '/api/admin/catalogue/$sectionId': typeof ApiAdminCatalogueSectionIdRouteWithChildren
  '/api/admin/leaderboard/$id': typeof ApiAdminLeaderboardIdRoute
  '/api/auth/me/activity': typeof ApiAuthMeActivityRoute
  '/api/admin/catalogue/$sectionId/publish': typeof ApiAdminCatalogueSectionIdPublishRoute
  '/api/auth/me/progress/$quizId': typeof ApiAuthMeProgressQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/levels': typeof ApiLevelsRoute
  '/api/submit': typeof ApiSubmitRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/api/': typeof ApiIndexRoute
  '/certificate/': typeof CertificateIndexRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/catalogue': typeof ApiAdminCatalogueRouteWithChildren
  '/api/admin/certificates': typeof ApiAdminCertificatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRouteWithChildren
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/certificates/$code': typeof ApiCertificatesCodeRoute
  '/api/quizzes/$id': typeof ApiQuizzesIdRoute
  '/api/quizzes/': typeof ApiQuizzesIndexRoute
  '/api/admin/catalogue/$sectionId': typeof ApiAdminCatalogueSectionIdRouteWithChildren
  '/api/admin/leaderboard/$id': typeof ApiAdminLeaderboardIdRoute
  '/api/auth/me/activity': typeof ApiAuthMeActivityRoute
  '/api/admin/catalogue/$sectionId/publish': typeof ApiAdminCatalogueSectionIdPublishRoute
  '/api/auth/me/progress/$quizId': typeof ApiAuthMeProgressQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/delete-data'
    | '/history'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/support'
    | '/terms'
    | '/admin'
    | '/wallet'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/levels'
    | '/api/submit'
    | '/certificate/$code'
    | '/quizzes/$id'
    | '/api/'
    | '/certificate/'
    | '/api/admin/audit-log'
    | '/api/admin/catalogue'
    | '/api/admin/certificates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/certificates/$code'
    | '/api/quizzes/$id'
    | '/api/quizzes/'
    | '/api/admin/catalogue/$sectionId'
    | '/api/admin/leaderboard/$id'
    | '/api/auth/me/activity'
    | '/api/admin/catalogue/$sectionId/publish'
    | '/api/auth/me/progress/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/delete-data'
    | '/history'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/support'
    | '/terms'
    | '/admin'
    | '/wallet'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/levels'
    | '/api/submit'
    | '/certificate/$code'
    | '/quizzes/$id'
    | '/api'
    | '/certificate'
    | '/api/admin/audit-log'
    | '/api/admin/catalogue'
    | '/api/admin/certificates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/certificates/$code'
    | '/api/quizzes/$id'
    | '/api/quizzes'
    | '/api/admin/catalogue/$sectionId'
    | '/api/admin/leaderboard/$id'
    | '/api/auth/me/activity'
    | '/api/admin/catalogue/$sectionId/publish'
    | '/api/auth/me/progress/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/delete-account'
    | '/delete-data'
    | '/history'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/support'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/wallet'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/levels'
    | '/api/submit'
    | '/certificate/$code'
    | '/quizzes/$id'
    | '/api/'
    | '/certificate/'
    | '/api/admin/audit-log'
    | '/api/admin/catalogue'
    | '/api/admin/certificates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/certificates/$code'
    | '/api/quizzes/$id'
    | '/api/quizzes/'
    | '/api/admin/catalogue/$sectionId'
    | '/api/admin/leaderboard/$id'
    | '/api/auth/me/activity'
    | '/api/admin/catalogue/$sectionId/publish'
    | '/api/auth/me/progress/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DeleteDataRoute: typeof DeleteDataRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiLevelsRoute: typeof ApiLevelsRoute
  ApiSubmitRoute: typeof ApiSubmitRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  QuizzesIdRoute: typeof QuizzesIdRoute
  ApiIndexRoute: typeof ApiIndexRoute
  CertificateIndexRoute: typeof CertificateIndexRoute
  ApiAdminAuditLogRoute: typeof ApiAdminAuditLogRoute
  ApiAdminCatalogueRoute: typeof ApiAdminCatalogueRouteWithChildren
  ApiAdminCertificatesRoute: typeof ApiAdminCertificatesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRouteWithChildren
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiCertificatesCodeRoute: typeof ApiCertificatesCodeRoute
  ApiQuizzesIdRoute: typeof ApiQuizzesIdRoute
  ApiQuizzesIndexRoute: typeof ApiQuizzesIndexRoute
  ApiAdminLeaderboardIdRoute: typeof ApiAdminLeaderboardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-data': {
      id: '/delete-data'
      path: '/delete-data'
      fullPath: '/delete-data'
      preLoaderRoute: typeof DeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/levels': {
      id: '/api/levels'
      path: '/api/levels'
      fullPath: '/api/levels'
      preLoaderRoute: typeof ApiLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit': {
      id: '/api/submit'
      path: '/api/submit'
      fullPath: '/api/submit'
      preLoaderRoute: typeof ApiSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/': {
      id: '/certificate/'
      path: '/certificate'
      fullPath: '/certificate/'
      preLoaderRoute: typeof CertificateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-log': {
      id: '/api/admin/audit-log'
      path: '/api/admin/audit-log'
      fullPath: '/api/admin/audit-log'
      preLoaderRoute: typeof ApiAdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/catalogue': {
      id: '/api/admin/catalogue'
      path: '/api/admin/catalogue'
      fullPath: '/api/admin/catalogue'
      preLoaderRoute: typeof ApiAdminCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/certificates': {
      id: '/api/admin/certificates'
      path: '/api/admin/certificates'
      fullPath: '/api/admin/certificates'
      preLoaderRoute: typeof ApiAdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/$code': {
      id: '/api/certificates/$code'
      path: '/api/certificates/$code'
      fullPath: '/api/certificates/$code'
      preLoaderRoute: typeof ApiCertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizzes/': {
      id: '/api/quizzes/'
      path: '/api/quizzes'
      fullPath: '/api/quizzes/'
      preLoaderRoute: typeof ApiQuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizzes/$id': {
      id: '/api/quizzes/$id'
      path: '/api/quizzes/$id'
      fullPath: '/api/quizzes/$id'
      preLoaderRoute: typeof ApiQuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/catalogue/$sectionId': {
      id: '/api/admin/catalogue/$sectionId'
      path: '/$sectionId'
      fullPath: '/api/admin/catalogue/$sectionId'
      preLoaderRoute: typeof ApiAdminCatalogueSectionIdRouteImport
      parentRoute: typeof ApiAdminCatalogueRoute
    }
    '/api/admin/leaderboard/$id': {
      id: '/api/admin/leaderboard/$id'
      path: '/api/admin/leaderboard/$id'
      fullPath: '/api/admin/leaderboard/$id'
      preLoaderRoute: typeof ApiAdminLeaderboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/activity': {
      id: '/api/auth/me/activity'
      path: '/activity'
      fullPath: '/api/auth/me/activity'
      preLoaderRoute: typeof ApiAuthMeActivityRouteImport
      parentRoute: typeof ApiAuthMeRoute
    }
    '/api/admin/catalogue/$sectionId/publish': {
      id: '/api/admin/catalogue/$sectionId/publish'
      path: '/publish'
      fullPath: '/api/admin/catalogue/$sectionId/publish'
      preLoaderRoute: typeof ApiAdminCatalogueSectionIdPublishRouteImport
      parentRoute: typeof ApiAdminCatalogueSectionIdRoute
    }
    '/api/auth/me/progress/$quizId': {
      id: '/api/auth/me/progress/$quizId'
      path: '/progress/$quizId'
      fullPath: '/api/auth/me/progress/$quizId'
      preLoaderRoute: typeof ApiAuthMeProgressQuizIdRouteImport
      parentRoute: typeof ApiAuthMeRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiAdminCatalogueSectionIdRouteChildren {
  ApiAdminCatalogueSectionIdPublishRoute: typeof ApiAdminCatalogueSectionIdPublishRoute
}

const ApiAdminCatalogueSectionIdRouteChildren: ApiAdminCatalogueSectionIdRouteChildren =
  {
    ApiAdminCatalogueSectionIdPublishRoute:
      ApiAdminCatalogueSectionIdPublishRoute,
  }

const ApiAdminCatalogueSectionIdRouteWithChildren =
  ApiAdminCatalogueSectionIdRoute._addFileChildren(
    ApiAdminCatalogueSectionIdRouteChildren,
  )

interface ApiAdminCatalogueRouteChildren {
  ApiAdminCatalogueSectionIdRoute: typeof ApiAdminCatalogueSectionIdRouteWithChildren
}

const ApiAdminCatalogueRouteChildren: ApiAdminCatalogueRouteChildren = {
  ApiAdminCatalogueSectionIdRoute: ApiAdminCatalogueSectionIdRouteWithChildren,
}

const ApiAdminCatalogueRouteWithChildren =
  ApiAdminCatalogueRoute._addFileChildren(ApiAdminCatalogueRouteChildren)

interface ApiAuthMeRouteChildren {
  ApiAuthMeActivityRoute: typeof ApiAuthMeActivityRoute
  ApiAuthMeProgressQuizIdRoute: typeof ApiAuthMeProgressQuizIdRoute
}

const ApiAuthMeRouteChildren: ApiAuthMeRouteChildren = {
  ApiAuthMeActivityRoute: ApiAuthMeActivityRoute,
  ApiAuthMeProgressQuizIdRoute: ApiAuthMeProgressQuizIdRoute,
}

const ApiAuthMeRouteWithChildren = ApiAuthMeRoute._addFileChildren(
  ApiAuthMeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DeleteDataRoute: DeleteDataRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiLevelsRoute: ApiLevelsRoute,
  ApiSubmitRoute: ApiSubmitRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  QuizzesIdRoute: QuizzesIdRoute,
  ApiIndexRoute: ApiIndexRoute,
  CertificateIndexRoute: CertificateIndexRoute,
  ApiAdminAuditLogRoute: ApiAdminAuditLogRoute,
  ApiAdminCatalogueRoute: ApiAdminCatalogueRouteWithChildren,
  ApiAdminCertificatesRoute: ApiAdminCertificatesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRouteWithChildren,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiCertificatesCodeRoute: ApiCertificatesCodeRoute,
  ApiQuizzesIdRoute: ApiQuizzesIdRoute,
  ApiQuizzesIndexRoute: ApiQuizzesIndexRoute,
  ApiAdminLeaderboardIdRoute: ApiAdminLeaderboardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
