import { fromMap, type SectionDefinition } from "./helpers.server";

type Facts = [string, string][];

const facts = (entries: Facts) =>
  fromMap(
    entries,
    (question) => question,
    (_question, answer) => `The correct answer is: ${answer}.`,
  );

const football: Facts = [
  ["Which country won the first FIFA World Cup in 1930?", "Uruguay"],
  ["How many players does one football team have on the pitch?", "11"],
  ["How long is a standard football match before added time?", "90 minutes"],
  ["What is awarded when a defender commits a foul inside their penalty area?", "A penalty kick"],
  ["What colour card means a player is sent off?", "Red"],
  ["What is the world's main international football tournament called?", "The FIFA World Cup"],
  ["Which body governs international association football?", "FIFA"],
  ["What is the area in front of a football goal called?", "The penalty area"],
  ["What is three goals by one player in a match called?", "A hat-trick"],
  ["What is the restart from the corner of the pitch called?", "A corner kick"],
  ["What is awarded when the ball crosses the sideline?", "A throw-in"],
  ["Which player may use their hands inside their own penalty area?", "The goalkeeper"],
  [
    "What is the rule that prevents an attacker gaining an unfair position near goal?",
    "The offside rule",
  ],
  [
    "What is the European club competition commonly called the Champions League?",
    "UEFA Champions League",
  ],
  ["Which country is home to the Premier League?", "England"],
  ["Which club plays home matches at Camp Nou?", "FC Barcelona"],
  ["Which club plays home matches at Anfield?", "Liverpool"],
  ["Which club is known as the Red Devils?", "Manchester United"],
  ["Which nation has won the most men's FIFA World Cups?", "Brazil"],
  ["What is the final match of a tournament called?", "The final"],
  ["What is the official who enforces the laws during a match called?", "The referee"],
  [
    "What is the area behind the goal where substitutes warm up often called?",
    "The touchline area",
  ],
  ["What is a pass that directly creates a goal called?", "An assist"],
  ["What is a goal scored directly from a free kick called?", "A direct free-kick goal"],
  ["What is the system of players' positions used by a coach called?", "A formation"],
  ["What is the group stage followed by in many tournaments?", "The knockout stage"],
  ["What is the African international football tournament called?", "The Africa Cup of Nations"],
  ["What is the South American international football tournament called?", "Copa America"],
  ["What is a match between local rivals called?", "A derby"],
  ["What is the official match ball used for?", "Playing the match"],
  ["What is a player's move from one club to another called?", "A transfer"],
  ["What does VAR stand for in football?", "Video Assistant Referee"],
  ["What is the result when both teams score the same number of goals?", "A draw"],
  ["What is the area where team substitutes sit called?", "The technical area"],
  ["What is the line marking the middle of the pitch called?", "The halfway line"],
];

const generalKnowledge: Facts = [
  ["What is the largest planet in our solar system?", "Jupiter"],
  ["What is the capital city of France?", "Paris"],
  ["How many continents are commonly recognised?", "Seven"],
  ["What gas do humans need to breathe?", "Oxygen"],
  ["What is the fastest land animal?", "The cheetah"],
  ["What is the chemical symbol for gold?", "Au"],
  ["Which ocean is the largest?", "The Pacific Ocean"],
  ["Who wrote Romeo and Juliet?", "William Shakespeare"],
  ["What is the currency of Japan?", "The yen"],
  ["How many sides does a hexagon have?", "Six"],
  ["What is the process by which plants make food using sunlight?", "Photosynthesis"],
  ["Which planet is known as the Red Planet?", "Mars"],
  ["What is the hardest natural substance?", "Diamond"],
  ["What is the longest river in South America?", "The Amazon River"],
  ["Which instrument measures temperature?", "A thermometer"],
  ["What is the smallest prime number?", "2"],
  ["Which organ pumps blood around the body?", "The heart"],
  ["What is the main language spoken in Brazil?", "Portuguese"],
  ["Who painted the Mona Lisa?", "Leonardo da Vinci"],
  ["What is the boiling point of water at sea level?", "100 degrees Celsius"],
  ["What is the largest mammal?", "The blue whale"],
  ["Which metal is liquid at room temperature?", "Mercury"],
  ["What is the study of stars and space called?", "Astronomy"],
  ["How many bones are in the adult human body approximately?", "206"],
  ["What is the capital city of Kenya?", "Nairobi"],
  ["Which ancient civilisation built the pyramids at Giza?", "The ancient Egyptians"],
  ["What is the square root of 64?", "8"],
  ["What is the largest hot desert?", "The Sahara"],
  ["Which blood cells help fight infection?", "White blood cells"],
  ["What is the name of Earth's natural satellite?", "The Moon"],
  ["Which force pulls objects toward Earth?", "Gravity"],
  ["What is the main ingredient in glass?", "Sand"],
  ["What is a word with the opposite meaning called?", "An antonym"],
  ["Which country gifted the Statue of Liberty to the United States?", "France"],
  ["What is the freezing point of water in Celsius?", "0 degrees"],
];

const moviesAndMusic: Facts = [
  ["What is the person who directs a film called?", "The director"],
  ["What award is commonly called an Oscar?", "The Academy Award"],
  ["What is the written story of a film called?", "The screenplay"],
  ["What is the music written for a film called?", "The film score"],
  ["What is a short preview of a film called?", "A trailer"],
  ["What is the main character in a story called?", "The protagonist"],
  ["What is the opposing character called?", "The antagonist"],
  ["What is a film made with drawn or computer-generated images called?", "An animated film"],
  ["What is the place where a film scene is recorded called?", "The set"],
  ["What is the process of selecting performers called?", "Casting"],
  ["How many strings does a standard guitar usually have?", "Six"],
  ["What is the speed of a piece of music called?", "Tempo"],
  ["What is a group of musicians who perform together called?", "A band"],
  ["What is the written form of a song called?", "Lyrics"],
  ["What is the repeated section of a song usually called?", "The chorus"],
  ["What device records or plays sound?", "A microphone or recorder"],
  ["What is a person who writes songs called?", "A songwriter"],
  ["What is a performance by one person called?", "A solo"],
  ["What is the musical distance between two notes called?", "An interval"],
  ["What is the loudness or softness of music called?", "Dynamics"],
  ["Which instrument has black and white keys?", "The piano"],
  ["Which family does the violin belong to?", "The string family"],
  ["What is a collection of songs released together called?", "An album"],
  ["What is a song released to promote an album often called?", "A single"],
  ["What is the person who leads an orchestra called?", "The conductor"],
  ["What is a film's age classification called?", "A rating"],
  ["What is the sequence of events in a film called?", "The plot"],
  ["What is a film made from existing footage called?", "A documentary"],
  ["What is a film's spoken language translation at the bottom of the screen called?", "Subtitles"],
  ["What is replacing spoken dialogue with another language called?", "Dubbing"],
  ["What is the visual design of a film's scenes called?", "Cinematography"],
  ["What is a humorous film usually called?", "A comedy"],
  ["What is a film about frightening events usually called?", "A horror film"],
  ["What is a film with futuristic science themes often called?", "Science fiction"],
  ["What is the final list of names shown in a film called?", "The credits"],
];

const gaming: Facts = [
  ["What is a video game played by many people online called?", "A multiplayer game"],
  ["What does RPG commonly stand for?", "Role-playing game"],
  ["What does FPS commonly stand for in gaming?", "First-person shooter"],
  ["What does NPC stand for?", "Non-player character"],
  ["What is the person controlled by the player called?", "The player character"],
  ["What is a game's rules and systems together called?", "Gameplay"],
  ["What is the main story of a game called?", "The campaign"],
  ["What is a game played competitively by professionals called?", "Esports"],
  ["What is a temporary improvement collected in a game called?", "A power-up"],
  ["What is a game area or stage called?", "A level"],
  ["What is a saved copy of game progress called?", "A save file"],
  ["What device is used to control many console games?", "A controller"],
  ["What is a game designed for phones called?", "A mobile game"],
  ["What is a game released for free but offering optional purchases called?", "Free-to-play"],
  ["What is downloadable extra game content called?", "DLC"],
  ["What is a very difficult enemy at the end of an area called?", "A boss"],
  ["What is the health of a character commonly shown as?", "A health bar"],
  ["What is a game played from the character's eyes called?", "First-person"],
  ["What is a game viewed from above or behind the character called?", "Third-person"],
  ["What does AI mean in games?", "Artificial intelligence"],
  ["What is a bug in a game?", "A programming or design error"],
  ["What is updating a game to fix issues called?", "Patching"],
  ["What is watching someone play a game online called?", "Game streaming"],
  ["What is a player-versus-player mode called?", "PvP"],
  ["What is a player-versus-environment mode called?", "PvE"],
  ["What is a game where players compete to be the last survivor often called?", "A battle royale"],
  ["What is a game built around exploring and collecting often called?", "An adventure game"],
  ["What is a game focused on solving challenges called?", "A puzzle game"],
  ["What is a game focused on managing resources and building called?", "A strategy game"],
  ["What is the visual appearance of a game called?", "Graphics"],
  ["What is the virtual world of a game called?", "The game world"],
  ["What is a player's online identity often called?", "A username"],
  ["What is a group of players who cooperate called?", "A team"],
  ["What is communication between players using voice called?", "Voice chat"],
  ["What is a game's release version available before launch often called?", "A beta"],
];

const footballSubtopicDefinitions: Array<readonly [string, string, string, Facts]> = [
  [
    "popular-world-cup",
    "World Cup",
    "World Cup tournaments, nations, records and famous moments.",
    [
      ["How often is the FIFA World Cup normally held?", "Every four years"],
      ["Which country hosted the first World Cup?", "Uruguay"],
      ["Which nation has won the most men's World Cups?", "Brazil"],
      ["What is the World Cup trophy called?", "The FIFA World Cup Trophy"],
      ["How many teams played at the 2022 men's World Cup?", "32"],
      ["What is the World Cup final?", "The match deciding the champion"],
      ["Which continent hosted the 2010 World Cup?", "Africa"],
      ["What stage follows the group stage?", "The knockout stage"],
    ],
  ],
  [
    "popular-premier-league",
    "Premier League",
    "English Premier League clubs, records, rules and rivalries.",
    [
      ["In which country is the Premier League played?", "England"],
      ["How many clubs compete in a Premier League season?", "20"],
      ["How many points is a league win worth?", "3"],
      ["What is the Premier League trophy awarded for?", "Finishing top of the league"],
      ["Which club plays at Anfield?", "Liverpool"],
      ["Which club plays at Old Trafford?", "Manchester United"],
      ["What happens to the bottom three clubs?", "They are relegated"],
      ["What is an English top-flight match between rivals called?", "A derby"],
    ],
  ],
  [
    "popular-champions-league",
    "Champions League",
    "UEFA Champions League clubs, finals, history and European competition.",
    [
      ["What does UEFA stand for?", "Union of European Football Associations"],
      ["Which clubs compete in the Champions League?", "Top European clubs"],
      ["What does the winner receive?", "The Champions League trophy"],
      ["What stage follows the group or league phase?", "The knockout phase"],
      ["Which club plays at the Santiago Bernabeu?", "Real Madrid"],
      ["Which club is based in Munich?", "Bayern Munich"],
      ["What is the final match called?", "The Champions League final"],
      ["What does a two-leg tie contain?", "A first leg and a second leg"],
    ],
  ],
  [
    "popular-la-liga",
    "La Liga",
    "Spanish league clubs, stadiums, players and football history.",
    [
      ["In which country is La Liga played?", "Spain"],
      ["Which club plays at Camp Nou?", "FC Barcelona"],
      ["Which club is based in Madrid and wears white traditionally?", "Real Madrid"],
      ["What is La Liga's top division called?", "Primera Division"],
      ["What happens to clubs finishing at the bottom?", "They are relegated"],
      ["What is a Barcelona versus Real Madrid match called?", "El Clasico"],
      ["What is a league table used to show?", "Club standings"],
      ["What is a win worth in the table?", "Three points"],
    ],
  ],
  [
    "popular-serie-a",
    "Serie A",
    "Italian league clubs, stadiums, tactics and football traditions.",
    [
      ["In which country is Serie A played?", "Italy"],
      ["Which club plays at San Siro?", "AC Milan and Inter Milan"],
      ["What is an Inter Milan versus AC Milan match called?", "The Derby della Madonnina"],
      ["What does a league table rank?", "Teams by results and points"],
      ["How many points does a Serie A win usually earn?", "3"],
      ["Which city is home to Juventus?", "Turin"],
      ["What is the Italian top division called?", "Serie A"],
      ["What happens to the bottom clubs?", "They can be relegated"],
    ],
  ],
  [
    "popular-bundesliga",
    "Bundesliga",
    "German league clubs, stadiums, supporters and football history.",
    [
      ["In which country is the Bundesliga played?", "Germany"],
      ["Which club is based in Munich?", "Bayern Munich"],
      ["What is the Bundesliga's highest division called?", "The German top flight"],
      ["How many points does a league win earn?", "3"],
      ["What is a football club's home ground called?", "A stadium"],
      ["Which city is home to Borussia Dortmund?", "Dortmund"],
      ["What does promotion mean?", "Moving to a higher division"],
      ["What is the German national cup called?", "DFB-Pokal"],
    ],
  ],
  [
    "popular-african-football",
    "African Football",
    "African clubs, nations, competitions and football development.",
    [
      ["What is Africa's main men's international tournament called?", "The Africa Cup of Nations"],
      ["What organisation governs African football?", "CAF"],
      ["What does CAF stand for?", "Confederation of African Football"],
      ["What is a national team made up of?", "Players representing a country"],
      ["What is Africa's leading club competition called?", "The CAF Champions League"],
      ["Which country hosted the 2010 World Cup?", "South Africa"],
      ["What is a local football rivalry called?", "A derby"],
      ["What does a football academy develop?", "Young players"],
    ],
  ],
  [
    "popular-womens-football",
    "Women's Football",
    "Women's football competitions, pioneers, clubs and international history.",
    [
      ["What is the women's global international tournament called?", "The FIFA Women's World Cup"],
      ["Which body governs women's international football?", "FIFA"],
      ["What is a women's national team?", "A team representing a country"],
      ["What is the main objective in a football match?", "Score more goals than the opponent"],
      ["What is the referee responsible for?", "Enforcing the laws of the game"],
      ["What is a professional women's league?", "A competition for professional women's clubs"],
      ["What is a penalty kick awarded for?", "A qualifying foul in the penalty area"],
      ["What is a hat-trick?", "Three goals by one player"],
    ],
  ],
  [
    "popular-club-history",
    "Club History",
    "Football club origins, honours, rivalries, stadiums and traditions.",
    [
      ["What is a club's founding date?", "The date it was established"],
      ["What is a club crest?", "Its identifying emblem"],
      ["What is a club nickname?", "A familiar name used by supporters"],
      ["What is a home ground?", "The stadium where a club hosts matches"],
      ["What is a club honour?", "A competition or title it has won"],
      ["What is a club legend?", "A highly celebrated former or current player"],
      ["What is a rivalry?", "A longstanding competitive relationship"],
      ["What is a supporters' group?", "Organised fans of a club"],
    ],
  ],
  [
    "popular-famous-players",
    "Famous Players",
    "Football legends, positions, records and playing styles.",
    [
      ["What position usually protects the goal?", "Goalkeeper"],
      ["What does a striker primarily try to do?", "Score goals"],
      ["What is a playmaker known for?", "Creating chances"],
      ["What is a defender's main task?", "Stopping attacks"],
      ["What is a midfielder responsible for?", "Linking defence and attack"],
      ["What is a player's assist?", "A pass that directly leads to a goal"],
      ["What is a clean sheet?", "Conceding no goals"],
      ["What is a player's cap?", "An appearance for a national team"],
    ],
  ],
  [
    "popular-transfers",
    "Transfers",
    "Transfer windows, contracts, fees, scouting and player movement.",
    [
      ["What is a football transfer?", "A player's move between clubs"],
      ["What is a transfer fee?", "Money paid by a club for a player's registration"],
      ["What is a transfer window?", "A period when clubs can register transfers"],
      ["What is a free transfer?", "A move without a transfer fee after a contract ends"],
      ["What is a loan move?", "A temporary move to another club"],
      ["What is a contract?", "A formal agreement between player and club"],
      ["What is a medical in a transfer?", "A health assessment before signing"],
      ["What is a release clause?", "A contract condition allowing a transfer for a stated amount"],
    ],
  ],
  [
    "popular-football-rules",
    "Football Rules",
    "The laws of football, fouls, restarts, officials and match decisions.",
    [
      ["How many players start for one team?", "11"],
      ["What is offside designed to prevent?", "An unfair attacking advantage"],
      ["What card cautions a player?", "Yellow"],
      ["What card sends a player off?", "Red"],
      ["What restart follows the ball leaving over the sideline?", "A throw-in"],
      [
        "What restart follows an attacker touching the ball over their own goal line?",
        "A corner kick",
      ],
      ["Who keeps official match time?", "The referee"],
      ["What is a foul?", "An unfair infringement of the laws"],
    ],
  ],
];

const topic = (
  id: string,
  name: string,
  description: string,
  entries: Facts,
): SectionDefinition => ({
  id,
  name,
  description,
  difficulty: "Medium",
  target: 500,
  build: () => facts(entries),
});

const footballSubtopics: SectionDefinition[] = footballSubtopicDefinitions.map(
  ([id, name, description, entries]) => topic(id, name, description, entries),
);

export const popularTopicSections: SectionDefinition[] = [
  topic(
    "popular-football",
    "Football",
    "Clubs, competitions, rules, players and football history.",
    football,
  ),
  ...footballSubtopics,
  topic(
    "popular-general-knowledge",
    "General Knowledge",
    "A broad challenge across science, history, geography and everyday facts.",
    generalKnowledge,
  ),
  topic(
    "popular-movies-music",
    "Movies & Music",
    "Film language, music theory, performers and entertainment culture.",
    moviesAndMusic,
  ),
  topic(
    "popular-gaming",
    "Gaming",
    "Video game genres, mechanics, esports and gaming culture.",
    gaming,
  ),
];
