import { fromMap, type Draft, type SectionDefinition } from "./helpers.server";

/** Build a fact-recall section from a question/answer list. */
const facts = (entries: [string, string][]): Draft[] =>
  fromMap(
    entries,
    (k) => k,
    (_k, v) => `The correct answer is: ${v}.`,
  );

/* ------------------------------ Early years ----------------------------- */

const animalFacts: [string, string][] = [
  ["Which animal says 'moo'?", "A cow"],
  ["Which animal says 'meow'?", "A cat"],
  ["Which animal says 'woof'?", "A dog"],
  ["Which animal gives us wool?", "A sheep"],
  ["Which animal has a long trunk?", "An elephant"],
  ["Which animal is called the king of the jungle?", "A lion"],
  ["Which animal hops and has long ears?", "A rabbit"],
  ["Which animal lives in water and has fins?", "A fish"],
  ["Which animal has a very long neck?", "A giraffe"],
  ["Which bird cannot fly but swims well?", "A penguin"],
  ["Which animal carries its house on its back?", "A snail"],
  ["Which insect makes honey?", "A bee"],
  ["Which animal has black and white stripes?", "A zebra"],
  ["Which animal lays eggs and clucks?", "A hen"],
  ["Which animal is a baby cat called?", "A kitten"],
  ["What is a baby dog called?", "A puppy"],
  ["What is a baby cow called?", "A calf"],
  ["Which animal changes colour to hide?", "A chameleon"],
  ["Which animal has eight legs?", "A spider"],
  ["Which animal jumps and says 'ribbit'?", "A frog"],
  ["Which animal is the fastest on land?", "A cheetah"],
  ["Which animal sleeps hanging upside down?", "A bat"],
  ["Which animal has a shell and moves slowly?", "A tortoise"],
  ["Which animal barks and guards the home?", "A dog"],
  ["Which farm animal gives us milk?", "A cow"],
  ["Which animal has a mane?", "A lion"],
  ["Which sea animal is very big and sprays water?", "A whale"],
  ["Which animal likes to eat bananas and swings?", "A monkey"],
  ["Which bird says 'hoot' at night?", "An owl"],
  ["Which animal has feathers and can fly?", "A bird"],
];

const routineFacts: [string, string][] = [
  ["How many days are in one week?", "7"],
  ["Which day comes after Monday?", "Tuesday"],
  ["Which day comes before Friday?", "Thursday"],
  ["What do we call the first meal of the day?", "Breakfast"],
  ["When do we see the sun?", "During the day"],
  ["When do we see the moon and stars?", "At night"],
  ["What do we wear when it rains?", "A raincoat"],
  ["What do we use to see when it is dark?", "A light"],
  ["What should we do before eating?", "Wash our hands"],
  ["What do we brush every morning?", "Our teeth"],
  ["How many months are in a year?", "12"],
  ["Which month is the first of the year?", "January"],
  ["Which month is the last of the year?", "December"],
  ["What season is hot and sunny?", "Summer"],
  ["What falls from the sky when it rains?", "Water"],
  ["What do we call frozen water?", "Ice"],
  ["Where do we go to learn?", "School"],
  ["Who teaches us at school?", "A teacher"],
  ["What do we say when someone helps us?", "Thank you"],
  ["What do we say when we meet someone in the morning?", "Good morning"],
  ["Where do we sleep at night?", "In a bed"],
  ["What do we use to write?", "A pencil"],
  ["What colour is the sky on a clear day?", "Blue"],
  ["What colour is grass?", "Green"],
  ["How many hours are in one day?", "24"],
  ["What do we call the day after today?", "Tomorrow"],
  ["What do we call the day before today?", "Yesterday"],
  ["What do we wear on our feet?", "Shoes"],
  ["Which meal do we eat in the middle of the day?", "Lunch"],
  ["What must we do to stay clean?", "Take a bath"],
];

/* -------------------------------- Primary -------------------------------- */

const artsFacts: [string, string][] = [
  ["What are the three primary colours?", "Red, blue and yellow"],
  ["What colour do you get mixing red and yellow?", "Orange"],
  ["What colour do you get mixing blue and yellow?", "Green"],
  ["What colour do you get mixing red and blue?", "Purple"],
  ["How many lines are in a music staff?", "5"],
  ["What do we call a group of singers?", "A choir"],
  ["Which instrument has black and white keys?", "The piano"],
  [
    "Which instrument do you blow into and has strings? (trick)",
    "None — a flute is blown, a guitar is strung",
  ],
  ["Which instrument is played with a bow?", "The violin"],
  ["Which instrument is hit with sticks?", "The drum"],
  ["What do we call a picture of a person?", "A portrait"],
  ["What do we call a picture of the countryside?", "A landscape"],
  ["What tool do painters use to apply paint?", "A brush"],
  ["What do we call art made by carving?", "Sculpture"],
  ["What do we call a shape made of clay?", "Pottery"],
  ["What is the pattern of sound in music called?", "Rhythm"],
  ["What word means how loud or soft music is?", "Dynamics"],
  ["What do we call the speed of a song?", "Tempo"],
  ["What material is used for weaving baskets?", "Reeds or straw"],
  ["What do we call colours that are opposite on the colour wheel?", "Complementary colours"],
  ["What do we call drawing with only lines?", "A sketch"],
  ["Which colours are called warm colours?", "Red, orange and yellow"],
  ["Which colours are called cool colours?", "Blue, green and purple"],
  ["What do we call art printed from a carved block?", "A print"],
  ["What do we call the outline shape of an object?", "Its silhouette"],
  ["What is a repeated design called?", "A pattern"],
  ["What do we call folk stories told through dance?", "Traditional dance"],
  ["What do we call a song sung to a baby?", "A lullaby"],
  ["How many strings does a standard guitar have?", "6"],
  ["What do we call a picture made of small tiles?", "A mosaic"],
];

/* ------------------------------- Secondary -------------------------------- */

const secEconFacts: [string, string][] = [
  ["What is the study of how societies use scarce resources?", "Economics"],
  ["What does 'demand' mean in economics?", "The quantity buyers are willing to buy at a price"],
  ["What happens to demand when price rises (other things equal)?", "Demand falls"],
  ["What happens to supply when price rises?", "Supply rises"],
  ["What is the point where supply meets demand called?", "Equilibrium"],
  ["What is a general rise in prices called?", "Inflation"],
  ["What is money paid to a landlord for land use?", "Rent"],
  ["What is the reward for labour?", "Wages"],
  ["What is the reward for capital?", "Interest"],
  ["What is the reward for enterprise?", "Profit"],
  ["What do we call goods bought from other countries?", "Imports"],
  ["What do we call goods sold to other countries?", "Exports"],
  ["What is the value of the next best alternative given up?", "Opportunity cost"],
  ["What do we call the total output of a country in a year?", "Gross domestic product"],
  ["What is a tax on imported goods called?", "A tariff"],
  ["What kind of economy is planned by government?", "A command economy"],
  ["What kind of economy is guided by prices?", "A market economy"],
  ["What is a market with one seller called?", "A monopoly"],
  ["What is a market with many small sellers called?", "Perfect competition"],
  ["What are goods used to produce other goods called?", "Capital goods"],
  ["What is money set aside rather than spent?", "Savings"],
  ["What is spending on capital to earn future returns?", "Investment"],
  ["What is the central bank's main policy tool?", "The interest rate"],
  ["What do we call unemployment caused by an economic downturn?", "Cyclical unemployment"],
  ["What is a budget where spending exceeds revenue?", "A deficit budget"],
  ["What do we call a tax that takes a bigger share from high incomes?", "A progressive tax"],
  ["What is the division of production into specialised tasks?", "Division of labour"],
  ["What is a written statement of expected income and spending?", "A budget"],
  ["What is a business owned by shareholders called?", "A company"],
  ["What curve shows income inequality?", "The Lorenz curve"],
];

const secAgricFacts: [string, string][] = [
  ["What is the practice of growing crops and rearing animals?", "Agriculture"],
  ["What nutrient makes leaves green and is key in fertiliser?", "Nitrogen"],
  ["What do we call growing one crop on the same land each season?", "Monocropping"],
  ["What practice alternates crops season to season?", "Crop rotation"],
  ["What is decomposed organic matter used to enrich soil?", "Compost"],
  ["What soil type holds most water?", "Clay soil"],
  ["What soil type drains fastest?", "Sandy soil"],
  ["What is the best soil for most crops?", "Loam soil"],
  ["What do we call artificial watering of crops?", "Irrigation"],
  ["What is the removal of topsoil by wind or water?", "Soil erosion"],
  ["What do we call keeping animals for milk?", "Dairy farming"],
  ["What is a young cow called?", "A calf"],
  ["What is the female of a pig called?", "A sow"],
  ["Which pest destroys stored grain?", "The weevil"],
  ["What chemical kills weeds?", "A herbicide"],
  ["What chemical kills insects?", "An insecticide"],
  ["What do we call the pH level best for most crops?", "Slightly acidic to neutral (6–7)"],
  ["Which crop is a legume that fixes nitrogen?", "Beans"],
  ["What is planting trees among crops called?", "Agroforestry"],
  ["What do we call farm produce sold for cash?", "Cash crops"],
  ["What is the process of separating grain from stalks?", "Threshing"],
  ["What structure stores harvested grain?", "A granary"],
  ["What do we call raising fish for food?", "Aquaculture"],
  ["What do we call farming without synthetic chemicals?", "Organic farming"],
  ["Which animal disease is spread by tsetse flies?", "Trypanosomiasis"],
  ["What is a farm record of income and expenses called?", "Farm accounts"],
  ["What machine turns soil before planting?", "The plough"],
  ["What is the covering of soil with dry matter to keep moisture?", "Mulching"],
  ["What do we call removing weak seedlings to space a crop?", "Thinning"],
  ["What is the transfer of pollen to a stigma?", "Pollination"],
];

/* --------------------------------- College -------------------------------- */

const psychologyFacts: [string, string][] = [
  ["Who is regarded as the father of psychoanalysis?", "Sigmund Freud"],
  ["Which psychologist studied classical conditioning with dogs?", "Ivan Pavlov"],
  ["Which psychologist is known for operant conditioning?", "B. F. Skinner"],
  ["What is the hierarchy of needs named after?", "Abraham Maslow"],
  ["What is the top of Maslow's hierarchy?", "Self-actualisation"],
  ["Which brain part controls balance and coordination?", "The cerebellum"],
  ["Which brain part processes memory formation?", "The hippocampus"],
  ["Which chemical messengers act between neurons?", "Neurotransmitters"],
  ["Which neurotransmitter is linked to reward?", "Dopamine"],
  ["Which research design compares groups at one point in time?", "Cross-sectional"],
  ["Which design follows the same people over time?", "Longitudinal"],
  ["What is a testable prediction called?", "A hypothesis"],
  ["What is the group that receives no treatment?", "The control group"],
  ["What bias occurs when participants change because they are watched?", "The Hawthorne effect"],
  ["What term describes memory of facts and events?", "Declarative memory"],
  ["Roughly how many items fit in short-term memory?", "About seven"],
  ["Which stage theory of development was proposed by Piaget?", "Cognitive development"],
  ["What is Piaget's first stage called?", "Sensorimotor"],
  ["What is the tendency to conform to a group called?", "Conformity"],
  ["Which experiment studied obedience to authority?", "Milgram's experiment"],
  ["What is the fear response system in the brain?", "The amygdala"],
  ["What condition involves persistent low mood and loss of interest?", "Depression"],
  ["What therapy targets thoughts and behaviours?", "Cognitive behavioural therapy"],
  ["What is the mental discomfort from conflicting beliefs?", "Cognitive dissonance"],
  ["Which IQ score is defined as average?", "100"],
  ["What is a lasting change in behaviour due to experience?", "Learning"],
  [
    "What is the tendency to attribute others' actions to character?",
    "Fundamental attribution error",
  ],
  ["Which sleep stage contains most dreaming?", "REM sleep"],
  ["What is the statistical value showing relationship strength?", "The correlation coefficient"],
  ["What ethical requirement must participants give?", "Informed consent"],
];

/* ------------------------------ Professional ------------------------------ */

const marketingFacts: [string, string][] = [
  ["What are the four Ps of marketing?", "Product, price, place, promotion"],
  ["What is dividing a market into groups called?", "Segmentation"],
  ["What is the group a campaign is aimed at?", "The target audience"],
  ["What does CTR stand for?", "Click-through rate"],
  ["What does CAC stand for?", "Customer acquisition cost"],
  ["What does LTV measure?", "The lifetime value of a customer"],
  ["What is the percentage of visitors who take an action?", "Conversion rate"],
  ["What is optimising a site to rank in search results?", "SEO"],
  ["What is paid search advertising commonly called?", "PPC"],
  ["What is the stage-by-stage model of buyer journey called?", "The marketing funnel"],
  ["What testing compares two page versions?", "A/B testing"],
  ["What is a unique reason to buy from you called?", "The value proposition"],
  ["What is content designed to attract rather than interrupt?", "Inbound marketing"],
  ["What metric shows returned revenue per ad spend?", "ROAS"],
  ["What is a brand's visual and verbal system called?", "Brand identity"],
  ["What is the study of competitors' positions called?", "Competitive analysis"],
  ["What survey question measures loyalty on 0–10?", "Net promoter score"],
  ["What is email sent to a subscriber list called?", "Email marketing"],
  ["What is a person's fictional profile of an ideal buyer?", "A buyer persona"],
  ["What is the share of a market a company holds?", "Market share"],
  ["What pricing sets a high launch price?", "Price skimming"],
  ["What pricing sets a low launch price to gain share?", "Penetration pricing"],
  ["What is unpaid social reach called?", "Organic reach"],
  ["What analysis covers strengths, weaknesses, opportunities and threats?", "SWOT"],
  ["What is repeat exposure to the same audience called?", "Frequency"],
  ["What is the number of unique people who saw an ad?", "Reach"],
  ["What is a call to action?", "A prompt telling the user what to do next"],
  ["What legal rule governs EU customer data?", "GDPR"],
  ["What is influencer marketing?", "Paying trusted creators to promote a product"],
  ["What is retargeting?", "Advertising again to people who already visited"],
];

const logisticsFacts: [string, string][] = [
  ["What does SCM stand for?", "Supply chain management"],
  ["What is holding stock to meet demand called?", "Inventory"],
  ["What inventory method issues the oldest stock first?", "FIFO"],
  ["What is the time between order and delivery?", "Lead time"],
  ["What is stock kept for unexpected demand?", "Safety stock"],
  ["What system orders only what is needed, when needed?", "Just-in-time"],
  ["What document lists goods in a shipment?", "The packing list"],
  ["What document is the contract for sea carriage?", "The bill of lading"],
  ["What is the standard shipping container length (small)?", "20 feet"],
  ["What term means delivery duty paid by the seller?", "DDP"],
  ["What are international trade terms called?", "Incoterms"],
  ["What is the movement of goods within a warehouse?", "Materials handling"],
  ["What is a facility that consolidates shipments?", "A distribution centre"],
  ["What does 3PL mean?", "Third-party logistics"],
  ["What measures orders delivered complete and on time?", "OTIF"],
  ["What is the reverse flow of returned goods called?", "Reverse logistics"],
  ["What is the cost of holding stock called?", "Carrying cost"],
  ["What formula balances order and holding costs?", "Economic order quantity"],
  ["What barcode standard is used on retail products?", "EAN/UPC"],
  ["What technology reads tags without line of sight?", "RFID"],
  ["What is the last leg of delivery to the customer?", "Last-mile delivery"],
  ["What is combining several small loads into one?", "Consolidation"],
  ["What plan matches supply with forecast demand?", "Sales and operations planning"],
  ["What is a stock count done throughout the year?", "Cycle counting"],
  ["What is the difference between recorded and actual stock?", "Inventory variance"],
  ["What warehouse method moves goods straight from inbound to outbound?", "Cross-docking"],
  ["What is the software that runs a warehouse called?", "A WMS"],
  ["What term describes running out of stock?", "A stockout"],
  ["What is the ratio of sales to average inventory?", "Inventory turnover"],
  ["What is a supplier scorecard used for?", "Measuring supplier performance"],
];

const telecomFacts: [string, string][] = [
  ["What does GSM stand for?", "Global System for Mobile communications"],
  ["Which generation introduced mass mobile broadband?", "4G LTE"],
  ["What is the main advantage of 5G over 4G?", "Much lower latency and higher capacity"],
  ["What unit measures signal frequency?", "The hertz"],
  ["What unit expresses signal power ratio?", "The decibel"],
  ["What device converts digital to analogue for a line?", "A modem"],
  ["What carries light signals over long distances?", "Optical fibre"],
  ["What is the loss of signal strength over distance?", "Attenuation"],
  ["What is unwanted signal interference between pairs?", "Crosstalk"],
  ["Which multiplexing shares a fibre by wavelength?", "WDM"],
  ["Which multiplexing shares a channel by time slot?", "TDM"],
  ["What is the area served by one mobile mast?", "A cell"],
  ["What happens when a call moves between cells?", "Handover"],
  ["What identifies a SIM subscriber?", "The IMSI"],
  ["What identifies the handset itself?", "The IMEI"],
  ["What protocol carries voice over the internet?", "VoIP"],
  ["What is the delay in a network called?", "Latency"],
  ["What is variation in packet delay called?", "Jitter"],
  ["What is the maximum data rate of a link?", "Bandwidth"],
  ["Which satellite orbit is used for TV broadcast?", "Geostationary"],
  ["What antenna type focuses signal in one direction?", "A directional antenna"],
  ["What band does Wi-Fi commonly use?", "2.4 GHz and 5 GHz"],
  ["What does PSTN stand for?", "Public switched telephone network"],
  ["What converts analogue voice to digital samples?", "A codec"],
  ["What sampling rate is used for standard telephony?", "8 kHz"],
  ["What is the standard voice channel bit rate?", "64 kbps"],
  ["What does SLA stand for in telecoms?", "Service level agreement"],
  ["What network topology connects every node to a central switch?", "Star"],
  ["What does FTTH mean?", "Fibre to the home"],
  ["What tool locates a break in a fibre?", "An OTDR"],
];

const energyFacts: [string, string][] = [
  ["Which renewable source uses sunlight directly?", "Solar photovoltaic"],
  ["Which renewable source uses moving air?", "Wind"],
  ["Which renewable source uses falling water?", "Hydropower"],
  ["Which renewable source uses heat from the earth?", "Geothermal"],
  ["What converts sunlight directly into electricity?", "A photovoltaic cell"],
  ["What device converts DC to AC in a solar system?", "An inverter"],
  ["What stores solar energy for night use?", "A battery bank"],
  ["What controls charging of a solar battery?", "A charge controller"],
  ["What is the standard test irradiance for PV panels?", "1000 W/m²"],
  ["What angle should a panel face for best yield?", "Tilted toward the equator at site latitude"],
  ["What reduces PV output most on a clear day?", "High cell temperature"],
  ["What is the ratio of actual to rated output over time?", "Capacity factor"],
  ["What is a wind turbine's rotating part called?", "The rotor"],
  ["What limits maximum wind turbine efficiency to 59.3%?", "The Betz limit"],
  ["What is biomass energy made from?", "Organic plant and animal matter"],
  ["What gas is produced by anaerobic digestion?", "Biogas (mainly methane)"],
  ["What is the main greenhouse gas from fossil fuels?", "Carbon dioxide"],
  ["What certificate proves renewable generation?", "A renewable energy certificate"],
  ["What is feeding surplus solar back to the grid called?", "Net metering"],
  ["What device measures electrical energy use?", "A kilowatt-hour meter"],
  ["What is one kilowatt-hour?", "One kilowatt used for one hour"],
  ["What is the grid frequency in most of Africa and Europe?", "50 Hz"],
  ["What protects a PV array from lightning surges?", "A surge protection device"],
  ["What is a microgrid?", "A local grid that can run independently"],
  ["What is energy that cannot be replenished called?", "Non-renewable energy"],
  ["What is the efficiency of a typical silicon PV panel?", "About 18–22%"],
  ["What is the term for reducing energy waste?", "Energy efficiency"],
  ["Which fuel cell fuel is most common?", "Hydrogen"],
  ["What does an energy audit do?", "Identifies where energy is used and wasted"],
  ["What is the levelised cost of energy?", "Lifetime cost divided by lifetime output"],
];

const aviationFacts: [string, string][] = [
  ["What force lifts an aircraft?", "Lift"],
  ["What force opposes thrust?", "Drag"],
  ["Which surface controls roll?", "The ailerons"],
  ["Which surface controls pitch?", "The elevator"],
  ["Which surface controls yaw?", "The rudder"],
  ["What instrument shows altitude?", "The altimeter"],
  ["What instrument shows airspeed?", "The airspeed indicator"],
  ["What is the angle between wing chord and airflow?", "Angle of attack"],
  ["What happens when the critical angle of attack is exceeded?", "A stall"],
  ["What are devices that increase lift at low speed?", "Flaps"],
  ["What is the international aviation body?", "ICAO"],
  ["What is the recorder that stores flight data called?", "The flight data recorder"],
  ["What is a pre-flight document listing the route?", "The flight plan"],
  ["What is the term for taking off into the wind?", "Headwind take-off"],
  ["What is standard sea-level pressure?", "1013.25 hPa"],
  ["What separates aircraft in controlled airspace?", "Air traffic control"],
  ["What does METAR provide?", "A routine aviation weather report"],
  ["What does VFR stand for?", "Visual flight rules"],
  ["What does IFR stand for?", "Instrument flight rules"],
  ["What is a runway's number based on?", "Its magnetic heading"],
  ["What system guides aircraft to the runway in poor visibility?", "The ILS"],
  ["What is the aircraft's total weight limit for take-off?", "Maximum take-off weight"],
  ["What is the distribution of load in an aircraft called?", "Weight and balance"],
  ["What engine type uses a fan and turbine?", "The turbofan"],
  ["What is cabin altitude usually maintained near?", "8,000 feet"],
  ["What is the emergency squawk code for hijack?", "7500"],
  ["What is the emergency squawk code for radio failure?", "7600"],
  ["What is the general emergency squawk code?", "7700"],
  ["What is turbulence caused by clear air called?", "Clear air turbulence"],
  ["What checklist is used before landing?", "The landing checklist"],
];

const hospitalityFacts: [string, string][] = [
  ["What is the front-desk area of a hotel called?", "Reception"],
  ["What is the process of a guest arriving called?", "Check-in"],
  ["What is a room booked but not occupied called?", "A no-show"],
  ["What is the percentage of rooms sold called?", "Occupancy rate"],
  ["What is average revenue per available room?", "RevPAR"],
  ["What is the average price paid per room?", "ADR"],
  ["What department cleans the rooms?", "Housekeeping"],
  ["What is the food safety system based on hazard analysis?", "HACCP"],
  ["What is the safe cold-holding temperature for food?", "Below 5 °C"],
  ["What is the safe hot-holding temperature for food?", "Above 63 °C"],
  ["What is the danger zone for bacterial growth?", "5 °C to 63 °C"],
  ["What is the French kitchen brigade leader called?", "The chef de cuisine"],
  ["What is a set menu at a fixed price called?", "Table d'hôte"],
  ["What is a menu priced per dish called?", "À la carte"],
  ["What is the person who serves wine called?", "The sommelier"],
  ["What is a hotel's list of extra charges called?", "Incidentals"],
  ["What is the practice of selling a better room called?", "Upselling"],
  ["What is a booking held without payment called?", "A tentative reservation"],
  ["What is the term for guests staying past checkout?", "Late checkout"],
  ["What is the standard measure of guest satisfaction?", "Guest feedback score"],
  ["What is the term for cleaning a room after departure?", "Departure clean"],
  ["What is a service charge added to a bill?", "A gratuity"],
  ["What is contamination between raw and cooked food?", "Cross-contamination"],
  ["What is first-in-first-out used for in kitchens?", "Stock rotation"],
  ["What is the room type with two double beds?", "A double-double"],
  ["What is an event package including meals and room?", "Full board"],
  ["What does B&B stand for?", "Bed and breakfast"],
  ["What is a walk-in guest?", "A guest arriving without a reservation"],
  ["What system manages hotel bookings?", "A property management system"],
  ["What is the term for turning away a booked guest?", "Walking the guest"],
];

/* --------------------------- Section definitions --------------------------- */

const section = (
  id: string,
  name: string,
  description: string,
  difficulty: SectionDefinition["difficulty"],
  entries: [string, string][],
): SectionDefinition => ({ id, name, description, difficulty, build: () => facts(entries) });

export const earlyTopicSections: SectionDefinition[] = [
  section(
    "early-animals",
    "Animals Around Us",
    "Farm, wild and sea animals for the youngest learners.",
    "Easy",
    animalFacts,
  ),
  section(
    "early-routines",
    "Days, Weather & Routines",
    "Days of the week, weather and everyday good habits.",
    "Easy",
    routineFacts,
  ),
];

export const primaryTopicSections: SectionDefinition[] = [
  section(
    "primary-arts",
    "Creative Arts & Music",
    "Colours, drawing, instruments and rhythm for primary pupils.",
    "Easy",
    artsFacts,
  ),
];

export const secondaryTopicSections: SectionDefinition[] = [
  section(
    "secondary-economics",
    "Economics",
    "Demand, supply, markets, trade and national income.",
    "Medium",
    secEconFacts,
  ),
  section(
    "secondary-agriculture",
    "Agriculture",
    "Soils, crops, livestock and farm management.",
    "Medium",
    secAgricFacts,
  ),
];

export const collegeTopicSections: SectionDefinition[] = [
  section(
    "college-psychology",
    "Psychology",
    "Learning, memory, development, research methods and the brain.",
    "Medium",
    psychologyFacts,
  ),
];

export const professionalTopicSections: SectionDefinition[] = [
  section(
    "professional-marketing",
    "Marketing & Growth",
    "Segmentation, funnels, digital channels and campaign metrics.",
    "Medium",
    marketingFacts,
  ),
  section(
    "professional-logistics",
    "Logistics & Supply Chain",
    "Inventory, warehousing, incoterms and distribution performance.",
    "Medium",
    logisticsFacts,
  ),
  section(
    "professional-telecom",
    "Telecommunications",
    "Mobile networks, fibre, multiplexing and service quality.",
    "Hard",
    telecomFacts,
  ),
  section(
    "professional-renewable-energy",
    "Renewable Energy",
    "Solar, wind, storage, grid integration and efficiency.",
    "Hard",
    energyFacts,
  ),
  section(
    "professional-aviation",
    "Aviation Operations",
    "Flight principles, instruments, airspace and safety procedures.",
    "Hard",
    aviationFacts,
  ),
  section(
    "professional-hospitality",
    "Hospitality & Food Safety",
    "Front office, housekeeping, kitchen standards and guest metrics.",
    "Medium",
    hospitalityFacts,
  ),
];
